<?php

/**
 * BaseImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $picture
 * @property string $url
 * @property clob $content
 * @property integer $weight
 * @property enum $type
 * 
 * @method string  getTitle()   Returns the current record's "title" value
 * @method string  getPicture() Returns the current record's "picture" value
 * @method string  getUrl()     Returns the current record's "url" value
 * @method clob    getContent() Returns the current record's "content" value
 * @method integer getWeight()  Returns the current record's "weight" value
 * @method enum    getType()    Returns the current record's "type" value
 * @method Images  setTitle()   Sets the current record's "title" value
 * @method Images  setPicture() Sets the current record's "picture" value
 * @method Images  setUrl()     Sets the current record's "url" value
 * @method Images  setContent() Sets the current record's "content" value
 * @method Images  setWeight()  Sets the current record's "weight" value
 * @method Images  setType()    Sets the current record's "type" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('images');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 2,
             ),
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}