<?php

/**
 * BaseCase
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property string $url
 * @property clob $content
 * 
 * @method string getToken()   Returns the current record's "token" value
 * @method string getTitle()   Returns the current record's "title" value
 * @method string getUrl()     Returns the current record's "url" value
 * @method clob   getContent() Returns the current record's "content" value
 * @method Case   setToken()   Sets the current record's "token" value
 * @method Case   setTitle()   Sets the current record's "title" value
 * @method Case   setUrl()     Sets the current record's "url" value
 * @method Case   setContent() Sets the current record's "content" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseCase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('case');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}