<?php

/**
 * BaseWork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property string $picture
 * @property string $sub_description
 * @property timestamp $end_time
 * @property string $video
 * @property string $video_name
 * @property string $video_url
 * @property integer $weight
 * @property integer $classes_id
 * @property integer $user_id
 * @property Doctrine_Collection $Jobs
 * @property sfGuardUser $sfGuardUser
 * @property Classes $Classes
 * 
 * @method string              getToken()           Returns the current record's "token" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getPicture()         Returns the current record's "picture" value
 * @method string              getSubDescription()  Returns the current record's "sub_description" value
 * @method timestamp           getEndTime()         Returns the current record's "end_time" value
 * @method string              getVideo()           Returns the current record's "video" value
 * @method string              getVideoName()       Returns the current record's "video_name" value
 * @method string              getVideoUrl()        Returns the current record's "video_url" value
 * @method integer             getWeight()          Returns the current record's "weight" value
 * @method integer             getClassesId()       Returns the current record's "classes_id" value
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method Doctrine_Collection getJobs()            Returns the current record's "Jobs" collection
 * @method sfGuardUser         getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method Classes             getClasses()         Returns the current record's "Classes" value
 * @method Work                setToken()           Sets the current record's "token" value
 * @method Work                setTitle()           Sets the current record's "title" value
 * @method Work                setPicture()         Sets the current record's "picture" value
 * @method Work                setSubDescription()  Sets the current record's "sub_description" value
 * @method Work                setEndTime()         Sets the current record's "end_time" value
 * @method Work                setVideo()           Sets the current record's "video" value
 * @method Work                setVideoName()       Sets the current record's "video_name" value
 * @method Work                setVideoUrl()        Sets the current record's "video_url" value
 * @method Work                setWeight()          Sets the current record's "weight" value
 * @method Work                setClassesId()       Sets the current record's "classes_id" value
 * @method Work                setUserId()          Sets the current record's "user_id" value
 * @method Work                setJobs()            Sets the current record's "Jobs" collection
 * @method Work                setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * @method Work                setClasses()         Sets the current record's "Classes" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseWork extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('work');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sub_description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('end_time', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('video', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('video_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('video_url', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('classes_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Job as Jobs', array(
             'local' => 'id',
             'foreign' => 'work_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Classes', array(
             'local' => 'classes_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}