<?php

/**
 * BaseJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property clob $content
 * @property string $attachment
 * @property string $attachment_name
 * @property integer $work_id
 * @property integer $user_id
 * @property integer $weight
 * @property sfGuardUser $User
 * @property Work $Work
 * 
 * @method string      getToken()           Returns the current record's "token" value
 * @method string      getTitle()           Returns the current record's "title" value
 * @method clob        getContent()         Returns the current record's "content" value
 * @method string      getAttachment()      Returns the current record's "attachment" value
 * @method string      getAttachmentName()  Returns the current record's "attachment_name" value
 * @method integer     getWorkId()          Returns the current record's "work_id" value
 * @method integer     getUserId()          Returns the current record's "user_id" value
 * @method integer     getWeight()          Returns the current record's "weight" value
 * @method sfGuardUser getUser()            Returns the current record's "User" value
 * @method Work        getWork()            Returns the current record's "Work" value
 * @method Job         setToken()           Sets the current record's "token" value
 * @method Job         setTitle()           Sets the current record's "title" value
 * @method Job         setContent()         Sets the current record's "content" value
 * @method Job         setAttachment()      Sets the current record's "attachment" value
 * @method Job         setAttachmentName()  Sets the current record's "attachment_name" value
 * @method Job         setWorkId()          Sets the current record's "work_id" value
 * @method Job         setUserId()          Sets the current record's "user_id" value
 * @method Job         setWeight()          Sets the current record's "weight" value
 * @method Job         setUser()            Sets the current record's "User" value
 * @method Job         setWork()            Sets the current record's "Work" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('job');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('attachment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('attachment_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('work_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Work', array(
             'local' => 'work_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}