<?php

/**
 * BaseNeed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property string $description
 * @property integer $price
 * @property integer $user_id
 * @property boolean $is_finish
 * @property Doctrine_Collection $Ans
 * @property sfGuardUser $User
 * 
 * @method string              getToken()       Returns the current record's "token" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getPrice()       Returns the current record's "price" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method boolean             getIsFinish()    Returns the current record's "is_finish" value
 * @method Doctrine_Collection getAns()         Returns the current record's "Ans" collection
 * @method sfGuardUser         getUser()        Returns the current record's "User" value
 * @method Need                setToken()       Sets the current record's "token" value
 * @method Need                setTitle()       Sets the current record's "title" value
 * @method Need                setDescription() Sets the current record's "description" value
 * @method Need                setPrice()       Sets the current record's "price" value
 * @method Need                setUserId()      Sets the current record's "user_id" value
 * @method Need                setIsFinish()    Sets the current record's "is_finish" value
 * @method Need                setAns()         Sets the current record's "Ans" collection
 * @method Need                setUser()        Sets the current record's "User" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseNeed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('need');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 2000, array(
             'type' => 'string',
             'length' => 2000,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_finish', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ans', array(
             'local' => 'id',
             'foreign' => 'need_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}