<?php

/**
 * BaseClasses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $name
 * @property string $description
 * @property integer $user_id
 * @property Doctrine_Collection $Student
 * @property Doctrine_Collection $Teacher
 * @property Doctrine_Collection $Works
 * @property Doctrine_Collection $ClassesStudent
 * 
 * @method string              getToken()          Returns the current record's "token" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method Doctrine_Collection getStudent()        Returns the current record's "Student" collection
 * @method Doctrine_Collection getTeacher()        Returns the current record's "Teacher" collection
 * @method Doctrine_Collection getWorks()          Returns the current record's "Works" collection
 * @method Doctrine_Collection getClassesStudent() Returns the current record's "ClassesStudent" collection
 * @method Classes             setToken()          Sets the current record's "token" value
 * @method Classes             setName()           Sets the current record's "name" value
 * @method Classes             setDescription()    Sets the current record's "description" value
 * @method Classes             setUserId()         Sets the current record's "user_id" value
 * @method Classes             setStudent()        Sets the current record's "Student" collection
 * @method Classes             setTeacher()        Sets the current record's "Teacher" collection
 * @method Classes             setWorks()          Sets the current record's "Works" collection
 * @method Classes             setClassesStudent() Sets the current record's "ClassesStudent" collection
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseClasses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('classes');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Student', array(
             'refClass' => 'ClassesStudent',
             'local' => 'classes_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUser as Teacher', array(
             'local' => 'id',
             'foreign' => 'classes_id'));

        $this->hasMany('Work as Works', array(
             'local' => 'id',
             'foreign' => 'classes_id'));

        $this->hasMany('ClassesStudent', array(
             'local' => 'id',
             'foreign' => 'classes_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}