<?php

/**
 * BaseApply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $company
 * @property string $contacter
 * @property string $address
 * @property string $tel
 * @property string $content
 * 
 * @method string getCompany()   Returns the current record's "company" value
 * @method string getContacter() Returns the current record's "contacter" value
 * @method string getAddress()   Returns the current record's "address" value
 * @method string getTel()       Returns the current record's "tel" value
 * @method string getContent()   Returns the current record's "content" value
 * @method Apply  setCompany()   Sets the current record's "company" value
 * @method Apply  setContacter() Sets the current record's "contacter" value
 * @method Apply  setAddress()   Sets the current record's "address" value
 * @method Apply  setTel()       Sets the current record's "tel" value
 * @method Apply  setContent()   Sets the current record's "content" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseApply extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('apply');
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('contacter', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tel', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}