<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property string $sub_description
 * @property string $keywords
 * @property integer $category_id
 * @property integer $user_id
 * @property enum $price
 * @property boolean $is_security
 * @property string $attachment
 * @property string $attachment_name
 * @property integer $attachment_size
 * @property integer $read_num
 * @property string $picture
 * @property boolean $is_rank
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Records
 * @property Category $Category
 * 
 * @method string              getToken()           Returns the current record's "token" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getSubDescription()  Returns the current record's "sub_description" value
 * @method string              getKeywords()        Returns the current record's "keywords" value
 * @method integer             getCategoryId()      Returns the current record's "category_id" value
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method enum                getPrice()           Returns the current record's "price" value
 * @method boolean             getIsSecurity()      Returns the current record's "is_security" value
 * @method string              getAttachment()      Returns the current record's "attachment" value
 * @method string              getAttachmentName()  Returns the current record's "attachment_name" value
 * @method integer             getAttachmentSize()  Returns the current record's "attachment_size" value
 * @method integer             getReadNum()         Returns the current record's "read_num" value
 * @method string              getPicture()         Returns the current record's "picture" value
 * @method boolean             getIsRank()          Returns the current record's "is_rank" value
 * @method sfGuardUser         getUser()            Returns the current record's "User" value
 * @method Doctrine_Collection getRecords()         Returns the current record's "Records" collection
 * @method Category            getCategory()        Returns the current record's "Category" value
 * @method File                setToken()           Sets the current record's "token" value
 * @method File                setTitle()           Sets the current record's "title" value
 * @method File                setSubDescription()  Sets the current record's "sub_description" value
 * @method File                setKeywords()        Sets the current record's "keywords" value
 * @method File                setCategoryId()      Sets the current record's "category_id" value
 * @method File                setUserId()          Sets the current record's "user_id" value
 * @method File                setPrice()           Sets the current record's "price" value
 * @method File                setIsSecurity()      Sets the current record's "is_security" value
 * @method File                setAttachment()      Sets the current record's "attachment" value
 * @method File                setAttachmentName()  Sets the current record's "attachment_name" value
 * @method File                setAttachmentSize()  Sets the current record's "attachment_size" value
 * @method File                setReadNum()         Sets the current record's "read_num" value
 * @method File                setPicture()         Sets the current record's "picture" value
 * @method File                setIsRank()          Sets the current record's "is_rank" value
 * @method File                setUser()            Sets the current record's "User" value
 * @method File                setRecords()         Sets the current record's "Records" collection
 * @method File                setCategory()        Sets the current record's "Category" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sub_description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('price', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 1,
              1 => 2,
              2 => 3,
              3 => 4,
              4 => 5,
              5 => 6,
             ),
             'default' => 1,
             ));
        $this->hasColumn('is_security', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('attachment', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('attachment_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('attachment_size', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('read_num', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_rank', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('DownloadRecords as Records', array(
             'local' => 'id',
             'foreign' => 'file_id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}