<?php

/**
 * BaseTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property string $url
 * @property clob $content
 * @property integer $weight
 * 
 * @method string  getToken()   Returns the current record's "token" value
 * @method string  getTitle()   Returns the current record's "title" value
 * @method string  getUrl()     Returns the current record's "url" value
 * @method clob    getContent() Returns the current record's "content" value
 * @method integer getWeight()  Returns the current record's "weight" value
 * @method Topic   setToken()   Sets the current record's "token" value
 * @method Topic   setTitle()   Sets the current record's "title" value
 * @method Topic   setUrl()     Sets the current record's "url" value
 * @method Topic   setContent() Sets the current record's "content" value
 * @method Topic   setWeight()  Sets the current record's "weight" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('topic');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}