<?php

/**
 * BaseAns
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $content
 * @property string $attachment
 * @property string $attachment_name
 * @property integer $attachment_size
 * @property integer $need_id
 * @property integer $user_id
 * @property boolean $is_true
 * @property sfGuardUser $User
 * @property Need $Need
 * 
 * @method string      getToken()           Returns the current record's "token" value
 * @method string      getContent()         Returns the current record's "content" value
 * @method string      getAttachment()      Returns the current record's "attachment" value
 * @method string      getAttachmentName()  Returns the current record's "attachment_name" value
 * @method integer     getAttachmentSize()  Returns the current record's "attachment_size" value
 * @method integer     getNeedId()          Returns the current record's "need_id" value
 * @method integer     getUserId()          Returns the current record's "user_id" value
 * @method boolean     getIsTrue()          Returns the current record's "is_true" value
 * @method sfGuardUser getUser()            Returns the current record's "User" value
 * @method Need        getNeed()            Returns the current record's "Need" value
 * @method Ans         setToken()           Sets the current record's "token" value
 * @method Ans         setContent()         Sets the current record's "content" value
 * @method Ans         setAttachment()      Sets the current record's "attachment" value
 * @method Ans         setAttachmentName()  Sets the current record's "attachment_name" value
 * @method Ans         setAttachmentSize()  Sets the current record's "attachment_size" value
 * @method Ans         setNeedId()          Sets the current record's "need_id" value
 * @method Ans         setUserId()          Sets the current record's "user_id" value
 * @method Ans         setIsTrue()          Sets the current record's "is_true" value
 * @method Ans         setUser()            Sets the current record's "User" value
 * @method Ans         setNeed()            Sets the current record's "Need" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseAns extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ans');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('attachment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('attachment_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('attachment_size', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('need_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_true', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Need', array(
             'local' => 'need_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}