<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $slug
 * @property clob $content
 * @property integer $client_id
 * @property Client $Client
 * 
 * @method string  getTitle()     Returns the current record's "title" value
 * @method string  getSlug()      Returns the current record's "slug" value
 * @method clob    getContent()   Returns the current record's "content" value
 * @method integer getClientId()  Returns the current record's "client_id" value
 * @method Client  getClient()    Returns the current record's "Client" value
 * @method Page    setTitle()     Sets the current record's "title" value
 * @method Page    setSlug()      Sets the current record's "slug" value
 * @method Page    setContent()   Sets the current record's "content" value
 * @method Page    setClientId()  Sets the current record's "client_id" value
 * @method Page    setClient()    Sets the current record's "Client" value
 * 
 * @package    symfonyStudy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('slug_index', array(
             'fields' => 
             array(
              0 => 'slug',
              1 => 'client_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}