<?php

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property clob $content
 * @property integer $expert_id
 * @property integer $user_id
 * @property clob $answer_content
 * @property boolean $is_finish
 * @property sfGuardUser $User
 * @property Expert $Expert
 * 
 * @method string      getToken()          Returns the current record's "token" value
 * @method string      getTitle()          Returns the current record's "title" value
 * @method clob        getContent()        Returns the current record's "content" value
 * @method integer     getExpertId()       Returns the current record's "expert_id" value
 * @method integer     getUserId()         Returns the current record's "user_id" value
 * @method clob        getAnswerContent()  Returns the current record's "answer_content" value
 * @method boolean     getIsFinish()       Returns the current record's "is_finish" value
 * @method sfGuardUser getUser()           Returns the current record's "User" value
 * @method Expert      getExpert()         Returns the current record's "Expert" value
 * @method Question    setToken()          Sets the current record's "token" value
 * @method Question    setTitle()          Sets the current record's "title" value
 * @method Question    setContent()        Sets the current record's "content" value
 * @method Question    setExpertId()       Sets the current record's "expert_id" value
 * @method Question    setUserId()         Sets the current record's "user_id" value
 * @method Question    setAnswerContent()  Sets the current record's "answer_content" value
 * @method Question    setIsFinish()       Sets the current record's "is_finish" value
 * @method Question    setUser()           Sets the current record's "User" value
 * @method Question    setExpert()         Sets the current record's "Expert" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('expert_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('answer_content', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('is_finish', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Expert', array(
             'local' => 'expert_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}