<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $token
 * @property string $title
 * @property string $experter
 * @property string $sub_description
 * @property string $attachment
 * @property string $attachment_name
 * @property string $url
 * @property string $url_name
 * @property string $thumbnailsPath
 * @property integer $weight
 * 
 * @method string  getToken()           Returns the current record's "token" value
 * @method string  getTitle()           Returns the current record's "title" value
 * @method string  getExperter()        Returns the current record's "experter" value
 * @method string  getSubDescription()  Returns the current record's "sub_description" value
 * @method string  getAttachment()      Returns the current record's "attachment" value
 * @method string  getAttachmentName()  Returns the current record's "attachment_name" value
 * @method string  getUrl()             Returns the current record's "url" value
 * @method string  getUrlName()         Returns the current record's "url_name" value
 * @method string  getThumbnailsPath()  Returns the current record's "thumbnailsPath" value
 * @method integer getWeight()          Returns the current record's "weight" value
 * @method Video   setToken()           Sets the current record's "token" value
 * @method Video   setTitle()           Sets the current record's "title" value
 * @method Video   setExperter()        Sets the current record's "experter" value
 * @method Video   setSubDescription()  Sets the current record's "sub_description" value
 * @method Video   setAttachment()      Sets the current record's "attachment" value
 * @method Video   setAttachmentName()  Sets the current record's "attachment_name" value
 * @method Video   setUrl()             Sets the current record's "url" value
 * @method Video   setUrlName()         Sets the current record's "url_name" value
 * @method Video   setThumbnailsPath()  Sets the current record's "thumbnailsPath" value
 * @method Video   setWeight()          Sets the current record's "weight" value
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video');
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('experter', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('sub_description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('attachment', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('attachment_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('thumbnailsPath', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}