<?php

/**
 * ActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activity');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('n')
    	->select('n.id,n.token,n.title,n.created_at')
    	->orderBy('n.weight desc,n.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Activity',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('a')
    	->select('a.id,a.token,a.title,a.content,a.weight,a.created_at')
    	->orderBy('a.weight desc,a.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
}