<?php

/**
 * Advertising
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
class Advertising extends BaseAdvertising
{
	public function getTypeName() {
		switch ($this->getType()) { 
			case 1 : 
				return '首页头部';
				exit();
			case 2 : 
				return '首页中部';
				exit(); 
			case 3 : 
				return '内页右侧';
				exit(); 
			case 4 : 
				return '内页底部';
				exit();
			default:
				exit();
		};
	}
}