<?php

/**
 * ApplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Apply');
    }
    public function getPager($page){
    	 
    	$q =  $this->createQuery('a')
    	->select('a.id,a.company,a.contacter,a.address,a.tel,a.content,a.created_at')
    	->orderBy('a.created_at desc');
    	 
    	$pager = new sfDoctrinePager ( 'Apply',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    	 
    	return $pager;
    	 
    }
}