<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nxetd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Category.class.php,v 1.4 2013/06/04 01:11:42 zhaoy Exp $
 */
class Category extends BaseCategory {
	public function save(Doctrine_Connection $conn = null) {
		
		if (! $this->getToken ()) {
			$this->setToken ( sha1 ( time () . rand ( 11111, 99999 ) ) );
		}
		
		return parent::save ( $conn );
	}
	
// 	public function delete(Doctrine_Connection $conn = null) {
// 		foreach($this->Contents as $content){
// 			$content->delete();
// 		}
// 		parent::delete();
// 	}
	
	public function getIndentedName() {
		return str_repeat ( '+', $this ['level'] ) . ' ' . $this ['name'];
	}
	
	public function getTag2(){
		$tags = Doctrine::getTable('Tag')->findByCategoryId2($this->getId());
		
		return $tags;
	}
	
	public function getContentListPager($page,$limit=30)
	{
		$q = Doctrine::getTable('Content')
			->createQuery('c')
			->leftJoin('c.Category y')
			->where('y.id = ?',$this->getId())
			->orderBy('c.is_top desc,c.created_at');
		
		$pager = new sfDoctrinePager ( 'Content',  $limit);
		$pager->setQuery ( $q );
		$pager->setPage ( $page );
		$pager->init ();
		
		return $pager;
	}
	
}