<?php

/**
 * Classes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
class Classes extends BaseClasses
{
	public function save(Doctrine_Connection $conn = null) {
	
		if (! $this->getToken ()) {
			$this->setToken ( sha1 ( time () . rand ( 11111, 99999 ) ) );
		}
	
		return parent::save ( $conn );
	}
	public function delete(Doctrine_Connection $conn = null) {

		$work = $this->getWorks();
		
		foreach ($work as $recored) {
			$recored->classes_id = null;
			$recored->save();
		}
	

		$teaher = $this->getTeacher();
		
	    foreach ($teaher as $recored) {
			$recored->classes_id = null;
			$recored->save();
		}

		return parent::delete( $conn );
	}
}