<?php

/**
 * ClassesStudentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClassesStudentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClassesStudentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClassesStudent');
    }
}