<?php

/**
 * DownloadRecordsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DownloadRecordsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DownloadRecordsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DownloadRecords');
    }
    public function getResult($file_id,$user_id){
    
    	$q =  $this->createQuery('r')
    	->where('r.file_id = ?',$file_id)
    	->andWhere('r.user_id = ?',$user_id)
    	->count();
    
    	return $q;
    }
}