<?php

/**
 * ExpertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Expert');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('e')
    	->select('e.id,n.token,e.name,e.job,e.sub_description,e.created_at')
    	->orderBy('e.weight desc,e.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Expert',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getList(){
    
    	$q =  $this->createQuery('e')
    	->select('e.id,e.name')
    	->orderBy('e.weight desc,e.created_at desc');
    
    	return $q->execute();
    }
    public function getListAll(){
    
    	$q =  $this->createQuery('e')
    	->select('e.id,e.token,e.job,e.name,e.picture,e.weight,e.created_at')
    	->orderBy('e.weight desc,e.created_at desc');
    
    	return $q->execute();
    }
    public function getListTop($limit){
    
    	$q =  $this->createQuery('e')
    	->select('e.id,e.token,e.name,e.job,e.sub_description,e.direction,e.picture,e.weight,e.created_at')
    	->where('e.type = 2')
    	->orderBy('e.weight desc,e.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
    public function getListNormal($page){
    
    	$q =  $this->createQuery('e')
    	->select('e.id,e.token,e.name,e.job,e.sub_description,e.direction,e.picture,e.weight,e.created_at')
    	->where('e.type = 1')
    	->orderBy('e.weight desc,e.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Expert',  sfConfig::get('app_max_expert_list_page',3));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    	
    	return $pager;
    }
}