<?php

/**
 * JobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Job');
    }
    public function getPager($page,$work_token){
    
    	$q =  $this->createQuery('j')
    	->select('j.id,j.attachment,j.attachment_name,j.created_at,u.nick_name uname')
    	->leftJoin('j.User u')
    	->leftJoin('j.Work w')
    	->where('w.token = ?',$work_token)
    	->orderBy('j.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Job',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
    public function getResultNum($work_id){
    	$user = sfContext::getInstance()->getUser()->getGuardUser()->getId();
    	$q =  $this->createQuery('j')
    	->where('j.user_id = ?',$user)
    	->andWhere('j.work_id = ?',$work_id)
    	->count();
    	
    	return $q;
    }
    public function getMyPager($page){
    
    	$user = sfContext::getInstance()->getUser()->getGuardUser()->getId();
    	$q =  $this->createQuery('j')
    	->select('j.id,j.attachment,j.attachment_name,j.created_at,u.nick_name uname,w.title as work_title')
    	->leftJoin('j.User u')
    	->leftJoin('j.Work w')
    	->where('j.user_id = ?',$user)
    	->orderBy('j.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Job',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
}