<?php

/**
 * Link
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
class Link extends BaseLink
{

}