<?php

/**
 * LinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Link');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('l')
    	->select('l.id,l.title,l.url')
    	->orderBy('l.weight desc');
    
    	$pager = new sfDoctrinePager ( 'Link',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('i')
    	->select('i.id,i.title,i.url,i.weight')
    	->orderBy('i.weight desc')
    	->limit($limit);
    
    	return $q->execute();
    }
}