<?php

/**
 * NoticeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NoticeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NoticeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notice');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('n')
    	->select('n.id,n.token,n.title,n.created_at')
    	->orderBy('n.weight desc,n.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Notice',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('n')
    	->select('n.id,n.token,n.title,n.created_at')
    	->orderBy('n.weight desc,n.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
}