<?php

/**
 * QuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Question');
    }
    public function getPager($page,$type='all'){
    
    	$q =  $this->createQuery('q')
    	->select('q.id,q.token,q.title,q.content,u.nick_name as uname,q.created_at,e.name as ename')
    	->leftJoin('q.User u')
    	->leftJoin('q.Expert e')
    	->orderBy('q.created_at desc');
    	
    	if($type == 'finished'){
    		$q->andWhere('q.is_finish = 1');
    	}elseif($type == 'unfinished'){
    		$q->andWhere('q.is_finish = 0');
    	}
    		
    	$pager = new sfDoctrinePager ( 'Question',  sfConfig::get('app_max_question_list_page',20));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('q')
    	->select('q.id,q.token,q.title,q.is_finish,q.created_at,e.name as ename')
    	->leftJoin('q.Expert e')
    	->orderBy('q.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
    public function getFinishedList($limit){
    
    	$q =  $this->createQuery('q')
    	->select('q.id,q.token,q.title,q.is_finish,q.created_at,e.name as ename')
    	->leftJoin('q.Expert e')
    	->where('q.is_finish = 1')
    	->orderBy('q.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
    public function getUFinishedList($limit){
    
    	$q =  $this->createQuery('q')
    	->select('q.id,q.token,q.title,q.is_finish,q.created_at,e.name as ename')
    	->leftJoin('q.Expert e')
    	->where('q.is_finish = 0')
    	->orderBy('q.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
    public function getMyPager($page){
    
    	$user = sfContext::getInstance()->getUser()->getGuardUser()->getId();
    	$q =  $this->createQuery('q')
    	->select('q.id,q.token,q.title,q.content,u.nick_name as uname,q.created_at,e.name as ename')
    	->leftJoin('q.User u')
    	->leftJoin('q.Expert e')
    	->orderBy('q.created_at desc')
    	->where('q.user_id = ?', $user);
    	
    	$pager = new sfDoctrinePager ( 'Question',  sfConfig::get('app_max_question_list_page',20));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
}