<?php

/**
 * ShareTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShareTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShareTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Share');
    }
    public function getPager($page,$is_rank='all'){
    
    	$q =  $this->createQuery('s')
    	->select('s.id,s.token,s.title,s.is_rank,s.created_at,u.nick_name as uname')
    	->leftJoin('s.User u')
    	->orderBy('s.weight desc,s.created_at desc');
    	if($is_rank == 'rank'){
    		$q->andWhere('s.is_rank = 1');
    	}
    	$pager = new sfDoctrinePager ( 'Share',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getMyPager($page,$is_rank='all'){
    	$user = sfContext::getInstance()->getUser()->getGuardUser()->getId();
    	$q =  $this->createQuery('s')
    	->select('s.id,s.token,s.title,s.is_rank,s.created_at,u.nick_name as uname')
    	->leftJoin('s.User u')
    	->where('s.user_id = ?',$user)
    	->orderBy('s.weight desc,s.created_at desc');
    	
    	$pager = new sfDoctrinePager ( 'Share',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('s')
    	->select('s.id,s.token,s.title,s.picture,s.content,s.weight,s.created_at,u.nick_name as uname')
    	->leftJoin('s.User u')
    	->where('s.is_rank = 1')
    	->orderBy('s.weight desc,s.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
}