<?php

/**
 * SuccessCaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuccessCaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuccessCaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuccessCase');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('i')
    	->select('i.id,i.title,i.weight')
    	->orderBy('i.weight desc');
    
    	$pager = new sfDoctrinePager ( 'Images',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('s')
    	->select('s.id,s.title,is.url,s.weight,s.token,s.created_at')
    	->orderBy('s.weight desc,s.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
}