<?php

/**
 * TopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TopicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Topic');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('t')
    	->select('t.id,t.token,t.title,t.weight')
    	->orderBy('t.weight desc,t.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Topic',  sfConfig::get('app_max_list_page',30));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('t')
    	->select('t.id,t.title,t.url,t.weight')
    	->orderBy('t.weight desc,t.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
}