<?php

/**
 * WorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Work');
    }
    public function getPager($page){
    
    	$q =  $this->createQuery('w')
    	->select('w.id,w.token,w.title,w.sub_description,w.end_time,w.created_at')
    	->orderBy('w.weight desc,w.created_at desc');
    
    	$pager = new sfDoctrinePager ( 'Work',  sfConfig::get('app_max_list_page',20));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
    public function getList($limit){
    
    	$q =  $this->createQuery('w')
    	->select('w.id,w.token,w.title,w.sub_description,w.picture,w.weight,w.created_at')
    	->orderBy('w.weight desc,w.created_at desc')
    	->limit($limit);
    
    	return $q->execute();
    }
    public function getMyPager($page){
    
    	$user = sfContext::getInstance()->getUser()->getGuardUser()->getId();
    	$q =  $this->createQuery('w')
    	->select('w.id,w.token,w.title,w.sub_description,w.end_time,w.created_at,w.classes_id')
    	->orderBy('w.weight desc,w.created_at desc')
    	->where('w.user_id = ? ', $user);
    
    	$pager = new sfDoctrinePager ( 'Work',  sfConfig::get('app_max_list_page',20));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
    public function getListPager($search_params, $page){
    
    	$q =  $this->createQuery('w')
    	->select('w.id,w.token,w.title,w.sub_description,w.end_time,w.created_at')
    	->leftJoin('w.sfGuardUser u')
    	->orderBy('w.weight desc,w.created_at desc');
    	
        if (isset($search_params['title']) && $search_params['title']) {
        	$q ->andwhere('w.title like ?', '%'.$search_params['title'].'%');
        }
    	if (isset($search_params['username']) && $search_params['username']) {
        	$q ->andWhere('u.username like ?', '%'.$search_params['username'].'%');
        } 
    
    	$pager = new sfDoctrinePager ( 'Work',  sfConfig::get('app_max_list_page',20));
    	$pager->setQuery ( $q );
    	$pager->setPage ( $page );
    	$pager->init ();
    
    	return $pager;
    
    }
}