<?php

/**
 * Work
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
class Work extends BaseWork
{
	public function save(Doctrine_Connection $conn = null) {
		if (! $this->getToken ()) {
			$this->setToken ( md5(uniqid(rand(), true)));//sha1 ( time () . rand ( 11111, 99999 ) ) );
		}
		parent::save ( $conn );
	}
	public function canAddJob(){
		$resust = Doctrine::getTable('Job')->getResultNum($this->id);
		if($this->getDateTimeObject('end_time')->format('Y-m-d').' 23:59:59' > date('Y-m-d H:i:s',time()) && $resust == 0){
			return true;
		}else{
			return false;
		}
	}
}