# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

default:
  is_secure: true
  
ajaxAddQuestion:
  is_secure: false
  
ajaxAddApply:
  is_secure: false
  
ajaxAddNeed:
  is_secure: false
  
ajaxAddNeedAns:
  is_secure: false
  
ajaxAddDocument:
  is_secure: false
