<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/27 15:24:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bzr',
  'username' => 'root',
  'password' => 123456,
  'encoding' => 'UTF8',
  'name' => 'doctrine',
)),);
