<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/08/27 15:24:23
sfConfig::add(array(
  'mod_sfcryptocaptcha_enabled' => true,
  'mod_sfcryptocaptcha_view_class' => 'sfPHP',
));
