<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/08/27 15:24:22
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'bbssignin' => 
  array (
    'is_secure' => false,
  ),
  'bbsfrontendsignin' => 
  array (
    'is_secure' => false,
  ),
  'frontendsignin' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
