<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/08/27 15:24:23
$this->security = array (
  'captcha' => 
  array (
    'is_secure' => false,
  ),
  'captchademo' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
