<?php

/**
 * sfGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nxetd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: sfGuardPermission.class.php,v 1.2 2012/05/14 07:01:53 zhaoy Exp $
 */
class sfGuardPermission extends PluginsfGuardPermission
{
	public function getAction()
	{
		
		$permission_name = $this->getName();
		
		if(!empty($permission_name))
		{
			$tmp = explode('_', $permission_name);
			if(!isset($tmp[1]))
				return false;
			$action = false;
			switch ($tmp[1]) {
				
				case '添加':
					$action = 'add';
					break;
				case '删除':
					$action = 'delete';
					break;
				case '修改':
					$action = 'update';
					break;
				case '查询':
					$action = 'select';
					break;
				default:
					$action = false;
					break;
			}
			return $action;
		}
		return false;
	}
}