<?php

/**
 * sfGuardGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nxetd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: sfGuardGroup.class.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
class sfGuardGroup extends PluginsfGuardGroup
{

}