<?php

/**
 * sfGuardGroupPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    nxetd
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: sfGuardGroupPermission.class.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
class sfGuardGroupPermission extends PluginsfGuardGroupPermission
{

}