<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    public function getUserListQuery($query_params)
    {
    	$q = $this->createQuery('u')
    			->leftJoin('u.Groups g')
    			->orderBy('u.created_at desc');
    	
//     	if(sfContext::getInstance()->getUser()->getGuardUser()->getIsSuperAdmin() == 0){
//     		$q->andWhere('u.is_super_admin != 1');
//     	}
    	
    	if(isset($query_params['username']))
    	{
    		$username = $query_params['username'];
    		$q->andWhere('u.username like ?','%'.$username.'%');
    	}
    	if(isset($query_params['group_id']))
    	{
    		$group_id = $query_params['group_id'];
    		$q->andWhere('g.id = ?',$group_id);
    	}
    	
    	return $q;
    }
    
    public function getStudentListPager($query_params,$page)
    {
    	$query_params['group_id'] = 1;
    	$q = $this->getUserListQuery($query_params);
    	
    	$pager = new sfDoctrinePager('sfGuardUser',sfConfig::get('app_max_user_list_page'));
    	$pager->setQuery( $q );
    	$pager->setPage($page);
    	$pager->init();
    	
    	return $pager;
    }
    public function getTeacherListPager($query_params,$page)
    {
    	$query_params['group_id'] = 2;
    	$q = $this->getUserListQuery($query_params);
    	 
    	$pager = new sfDoctrinePager('sfGuardUser',sfConfig::get('app_max_user_list_page'));
    	$pager->setQuery( $q );
    	$pager->setPage($page);
    	$pager->init();
    	 
    	return $pager;
    }
    
    public function getBackendUserQuery(){
    	$q = $this->createQuery('u')
  			->leftJoin('u.Groups g')
  			->where('g.name = ?','妇女网后台');
    	return $q;
    }
}