<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $real_name
 * @property string $nick_name
 * @property string $email_address
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property string $last_ip
 * @property string $customstatus
 * @property string $idiograph
 * @property string $introduce
 * @property enum $sex
 * @property timestamp $birthday
 * @property string $phone
 * @property string $adress
 * @property string $qq
 * @property string $card
 * @property integer $role_manager_bbs_id
 * @property integer $rank
 * @property integer $experience
 * @property enum $display_type
 * @property string $head_portrait
 * @property enum $questions
 * @property string $answer
 * @property string $token
 * @property integer $classes_id
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Classes
 * @property Doctrine_Collection $Work
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property Doctrine_Collection $Question
 * @property Doctrine_Collection $ClassesStudent
 * @property Expert $Expert
 * @property Doctrine_Collection $Shares
 * @property Doctrine_Collection $Files
 * @property Doctrine_Collection $Records
 * @property Doctrine_Collection $Needs
 * @property Doctrine_Collection $Ans
 * @property Doctrine_Collection $Job
 * 
 * @method string                getFirstName()             Returns the current record's "first_name" value
 * @method string                getLastName()              Returns the current record's "last_name" value
 * @method string                getRealName()              Returns the current record's "real_name" value
 * @method string                getNickName()              Returns the current record's "nick_name" value
 * @method string                getEmailAddress()          Returns the current record's "email_address" value
 * @method string                getUsername()              Returns the current record's "username" value
 * @method string                getAlgorithm()             Returns the current record's "algorithm" value
 * @method string                getSalt()                  Returns the current record's "salt" value
 * @method string                getPassword()              Returns the current record's "password" value
 * @method boolean               getIsActive()              Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()             Returns the current record's "last_login" value
 * @method string                getLastIp()                Returns the current record's "last_ip" value
 * @method string                getCustomstatus()          Returns the current record's "customstatus" value
 * @method string                getIdiograph()             Returns the current record's "idiograph" value
 * @method string                getIntroduce()             Returns the current record's "introduce" value
 * @method enum                  getSex()                   Returns the current record's "sex" value
 * @method timestamp             getBirthday()              Returns the current record's "birthday" value
 * @method string                getPhone()                 Returns the current record's "phone" value
 * @method string                getAdress()                Returns the current record's "adress" value
 * @method string                getQq()                    Returns the current record's "qq" value
 * @method string                getCard()                  Returns the current record's "card" value
 * @method integer               getRoleManagerBbsId()      Returns the current record's "role_manager_bbs_id" value
 * @method integer               getRank()                  Returns the current record's "rank" value
 * @method integer               getExperience()            Returns the current record's "experience" value
 * @method enum                  getDisplayType()           Returns the current record's "display_type" value
 * @method string                getHeadPortrait()          Returns the current record's "head_portrait" value
 * @method enum                  getQuestions()             Returns the current record's "questions" value
 * @method string                getAnswer()                Returns the current record's "answer" value
 * @method string                getToken()                 Returns the current record's "token" value
 * @method integer               getClassesId()             Returns the current record's "classes_id" value
 * @method Doctrine_Collection   getGroups()                Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()           Returns the current record's "Permissions" collection
 * @method Doctrine_Collection   getClasses()               Returns the current record's "Classes" collection
 * @method Doctrine_Collection   getWork()                  Returns the current record's "Work" collection
 * @method Doctrine_Collection   getSfGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()      Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()          Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()        Returns the current record's "ForgotPassword" value
 * @method Doctrine_Collection   getQuestion()              Returns the current record's "Question" collection
 * @method Doctrine_Collection   getClassesStudent()        Returns the current record's "ClassesStudent" collection
 * @method Expert                getExpert()                Returns the current record's "Expert" value
 * @method Doctrine_Collection   getShares()                Returns the current record's "Shares" collection
 * @method Doctrine_Collection   getFiles()                 Returns the current record's "Files" collection
 * @method Doctrine_Collection   getRecords()               Returns the current record's "Records" collection
 * @method Doctrine_Collection   getNeeds()                 Returns the current record's "Needs" collection
 * @method Doctrine_Collection   getAns()                   Returns the current record's "Ans" collection
 * @method Doctrine_Collection   getJob()                   Returns the current record's "Job" collection
 * @method sfGuardUser           setFirstName()             Sets the current record's "first_name" value
 * @method sfGuardUser           setLastName()              Sets the current record's "last_name" value
 * @method sfGuardUser           setRealName()              Sets the current record's "real_name" value
 * @method sfGuardUser           setNickName()              Sets the current record's "nick_name" value
 * @method sfGuardUser           setEmailAddress()          Sets the current record's "email_address" value
 * @method sfGuardUser           setUsername()              Sets the current record's "username" value
 * @method sfGuardUser           setAlgorithm()             Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                  Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()              Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()              Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()             Sets the current record's "last_login" value
 * @method sfGuardUser           setLastIp()                Sets the current record's "last_ip" value
 * @method sfGuardUser           setCustomstatus()          Sets the current record's "customstatus" value
 * @method sfGuardUser           setIdiograph()             Sets the current record's "idiograph" value
 * @method sfGuardUser           setIntroduce()             Sets the current record's "introduce" value
 * @method sfGuardUser           setSex()                   Sets the current record's "sex" value
 * @method sfGuardUser           setBirthday()              Sets the current record's "birthday" value
 * @method sfGuardUser           setPhone()                 Sets the current record's "phone" value
 * @method sfGuardUser           setAdress()                Sets the current record's "adress" value
 * @method sfGuardUser           setQq()                    Sets the current record's "qq" value
 * @method sfGuardUser           setCard()                  Sets the current record's "card" value
 * @method sfGuardUser           setRoleManagerBbsId()      Sets the current record's "role_manager_bbs_id" value
 * @method sfGuardUser           setRank()                  Sets the current record's "rank" value
 * @method sfGuardUser           setExperience()            Sets the current record's "experience" value
 * @method sfGuardUser           setDisplayType()           Sets the current record's "display_type" value
 * @method sfGuardUser           setHeadPortrait()          Sets the current record's "head_portrait" value
 * @method sfGuardUser           setQuestions()             Sets the current record's "questions" value
 * @method sfGuardUser           setAnswer()                Sets the current record's "answer" value
 * @method sfGuardUser           setToken()                 Sets the current record's "token" value
 * @method sfGuardUser           setClassesId()             Sets the current record's "classes_id" value
 * @method sfGuardUser           setGroups()                Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()           Sets the current record's "Permissions" collection
 * @method sfGuardUser           setClasses()               Sets the current record's "Classes" collection
 * @method sfGuardUser           setWork()                  Sets the current record's "Work" collection
 * @method sfGuardUser           setSfGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()      Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()          Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()        Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setQuestion()              Sets the current record's "Question" collection
 * @method sfGuardUser           setClassesStudent()        Sets the current record's "ClassesStudent" collection
 * @method sfGuardUser           setExpert()                Sets the current record's "Expert" value
 * @method sfGuardUser           setShares()                Sets the current record's "Shares" collection
 * @method sfGuardUser           setFiles()                 Sets the current record's "Files" collection
 * @method sfGuardUser           setRecords()               Sets the current record's "Records" collection
 * @method sfGuardUser           setNeeds()                 Sets the current record's "Needs" collection
 * @method sfGuardUser           setAns()                   Sets the current record's "Ans" collection
 * @method sfGuardUser           setJob()                   Sets the current record's "Job" collection
 * 
 * @package    bzr
 * @subpackage model
 * @author     gefei
 * @version    SVN: $Id: Builder.php,v 1.1 2012/05/04 06:47:28 zhaoy Exp $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('real_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nick_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('last_ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('customstatus', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('idiograph', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('introduce', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sex', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 1,
             ),
             'default' => 0,
             ));
        $this->hasColumn('birthday', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('adress', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('qq', 'string', 125, array(
             'type' => 'string',
             'length' => 125,
             ));
        $this->hasColumn('card', 'string', 125, array(
             'type' => 'string',
             'length' => 125,
             ));
        $this->hasColumn('role_manager_bbs_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('experience', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('display_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 1,
              2 => 2,
             ),
             'default' => 0,
             ));
        $this->hasColumn('head_portrait', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('questions', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 0,
              1 => 1,
              2 => 2,
              3 => 3,
              4 => 4,
              5 => 5,
              6 => 6,
              7 => 7,
             ),
             'default' => 0,
             ));
        $this->hasColumn('answer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('classes_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('Classes', array(
             'refClass' => 'ClassesStudent',
             'local' => 'user_id',
             'foreign' => 'classes_id'));

        $this->hasMany('Work', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Question', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('ClassesStudent', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('Expert', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Share as Shares', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('File as Files', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('DownloadRecords as Records', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Need as Needs', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Ans', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Job', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}