<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2013/09/05 14:36:22
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseclientformfilter' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/filter/doctrine/base/BaseClientFormFilter.class.php',
  'basepageformfilter' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/filter/doctrine/base/BasePageFormFilter.class.php',
  'baseformfilterdoctrine' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'clientformfilter' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/filter/doctrine/ClientFormFilter.class.php',
  'pageformfilter' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/filter/doctrine/PageFormFilter.class.php',
  'baseform' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/form/BaseForm.class.php',
  'baseclientform' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/form/doctrine/base/BaseClientForm.class.php',
  'basepageform' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/form/doctrine/base/BasePageForm.class.php',
  'baseformdoctrine' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/form/doctrine/BaseFormDoctrine.class.php',
  'clientform' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/form/doctrine/ClientForm.class.php',
  'pageform' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/form/doctrine/PageForm.class.php',

  // project_model
  'baseclient' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/model/doctrine/base/BaseClient.class.php',
  'basepage' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/model/doctrine/base/BasePage.class.php',
  'client' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/model/doctrine/Client.class.php',
  'clienttable' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/model/doctrine/ClientTable.class.php',
  'page' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/model/doctrine/Page.class.php',
  'pagetable' => 'F:/workspace/php/bzrLocal/bzrLocal/lib/model/doctrine/PageTable.class.php',

  // application
  'myuser' => 'F:/workspace/php/bzrLocal/bzrLocal/apps/fronted/lib/myUser.class.php',

  // modules
);
