<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/05 14:28:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfonyStudy',
  'username' => 'root',
  'password' => 123456,
  'name' => 'doctrine',
)),);
