<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('share', 'type');
        $this->addColumn('images', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => '1',
              1 => '2',
             ),
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('share', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => '1',
              1 => '2',
             ),
             'default' => '1',
             ));
        $this->removeColumn('images', 'type');
    }
}