<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('download_records', 'download_records_user_id_sf_guard_user_id', array(
             'name' => 'download_records_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('download_records', 'download_records_file_id_file_id', array(
             'name' => 'download_records_file_id_file_id',
             'local' => 'file_id',
             'foreign' => 'id',
             'foreignTable' => 'file',
             ));
        $this->addIndex('download_records', 'download_records_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('download_records', 'download_records_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('download_records', 'download_records_user_id_sf_guard_user_id');
        $this->dropForeignKey('download_records', 'download_records_file_id_file_id');
        $this->removeIndex('download_records', 'download_records_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('download_records', 'download_records_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }
}