<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('file', 'picture', 'string', '255', array(
             ));
        $this->addColumn('file', 'is_rank', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('file', 'picture');
        $this->removeColumn('file', 'is_rank');
    }
}