<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('job', 'job_work_id_work_id', array(
             'name' => 'job_work_id_work_id',
             'local' => 'work_id',
             'foreign' => 'id',
             'foreignTable' => 'work',
             ));
        $this->addIndex('job', 'job_work_id', array(
             'fields' => 
             array(
              0 => 'work_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('job', 'job_work_id_work_id');
        $this->removeIndex('job', 'job_work_id', array(
             'fields' => 
             array(
              0 => 'work_id',
             ),
             ));
    }
}