<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('ans', 'is_answer');
        $this->addColumn('ans', 'attachment_name', 'string', '255', array(
             ));
        $this->addColumn('ans', 'attachment_size', 'integer', '8', array(
             ));
        $this->addColumn('ans', 'is_true', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('file', 'attachment_size', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('ans', 'is_answer', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->removeColumn('ans', 'attachment_name');
        $this->removeColumn('ans', 'attachment_size');
        $this->removeColumn('ans', 'is_true');
        $this->removeColumn('file', 'attachment_size');
    }
}