<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('file', 'price', 'enum', '', array(
             'values' => 
             array(
              0 => '1',
              1 => '2',
              2 => '3',
              3 => '4',
              4 => '5',
              5 => '6',
             ),
             'default' => '1',
             ));
    }

    public function down()
    {

    }
}