<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('share', 'sub_description', 'string', '1000', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('share', 'sub_description');
    }
}