<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('file', 'read_num', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('file', 'read_num');
    }
}