<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('expert', 'expert_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user', 'sf_guard_user_classes_id_classes_id');
        $this->createForeignKey('classes_student', 'classes_student_user_id_sf_guard_user_id', array(
             'name' => 'classes_student_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('classes_student', 'classes_student_classes_id_classes_id', array(
             'name' => 'classes_student_classes_id_classes_id',
             'local' => 'classes_id',
             'foreign' => 'id',
             'foreignTable' => 'classes',
             ));
        $this->addIndex('classes_student', 'classes_student_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('classes_student', 'classes_student_classes_id', array(
             'fields' => 
             array(
              0 => 'classes_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('expert', 'expert_user_id_sf_guard_user_id', array(
             'name' => 'expert_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('sf_guard_user', 'sf_guard_user_classes_id_classes_id', array(
             'name' => 'sf_guard_user_classes_id_classes_id',
             'local' => 'classes_id',
             'foreign' => 'id',
             'foreignTable' => 'classes',
             ));
        $this->dropForeignKey('classes_student', 'classes_student_user_id_sf_guard_user_id');
        $this->dropForeignKey('classes_student', 'classes_student_classes_id_classes_id');
        $this->removeIndex('classes_student', 'classes_student_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('classes_student', 'classes_student_classes_id', array(
             'fields' => 
             array(
              0 => 'classes_id',
             ),
             ));
    }
}