<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('work', 'user_id');
        $this->addColumn('expert', 'user_id', 'integer', '8', array(
             ));
        $this->addColumn('work', 'classes_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('work', 'user_id', 'integer', '8', array(
             ));
        $this->removeColumn('expert', 'user_id');
        $this->removeColumn('work', 'classes_id');
    }
}