<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version33 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('classes', 'classes_user_id_sf_guard_user_id');
    }

    public function down()
    {
        $this->createForeignKey('classes', 'classes_user_id_sf_guard_user_id', array(
             'name' => 'classes_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
    }
}