<?php

/**
 * PluginsfGuardForgotPassword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: PluginsfGuardForgotPassword.class.php,v 1.1 2012/05/04 06:47:26 zhaoy Exp $
 */
abstract class PluginsfGuardForgotPassword extends BasesfGuardForgotPassword
{

}